<?php
if(Mage::getStoreConfig('evrijn/evrijn_group/enable',Mage::app()->getStore()) == 1):
$_product = Mage::registry('current_product');
?>
<script type="text/javascript">
var google_tag_params = { 
ecomm_prodid: '<?=$_product->getSku()?>',
ecomm_pagetype: 'product',
ecomm_totalvalue: '<? echo number_format($_product->getPrice(), 2) ?>'};
};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = <?=Mage::getStoreConfig('evrijn/evrijn_group/evrijn_input',Mage::app()->getStore())?>;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://googleads.g.doubleclick.net/pagead/viewthroughconversion/<?=Mage::getStoreConfig('evrijn/evrijn_group/evrijn_input',Mage::app()->getStore());?>/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<? endif;  ?>
